### ISSUE TITLE
Template plugin removed from Tinymce version 7

### ISSUE THREAD

**Issue by LucVK** [amidesfahani/filament-tinyeditor#52]
I get the following error stating that de template plugin is no longer available in the Tinymce free version.
How can I remove this plugin?

The following deprecated features are currently enabled and have been removed in TinyMCE 7.0. These features will no longer work and should be removed from the TinyMCE configuration. See https://www.tiny.cloud/docs/tinymce/7/migration-from-6x/ for more information.

Plugins:
- template

Options:
- templates

**Comment by amidesfahani** [comment]
Publish config file using this command:
`php artisan vendor:publish --tag="filament-tinyeditor-config"`
then customize your preferred plugins

**Comment by JoanVt** [comment]
@LucVK 
Is a warning because this package should be splitted in one new version with TinyMCE version 7 as long as templates is deprecated in this new version.

However, you can modify the tiny-editor component by copying it in your resources/views and modify that directive:

```
 x-data="tinyeditor({
           ...
            toolbar_sticky: {{ $getToolbarSticky() ? 'true' : 'false' }},
            templates: '{{ $getTemplates() }}',
            ...
        })">
```

Not sure, but reading the doc (https://www.tiny.cloud/docs/tinymce/7/advanced-templates/)
you have to have something like this:
```
 x-data="tinyeditor({
           ...
            toolbar_sticky: {{ $getToolbarSticky() ? 'true' : 'false' }},
            advtemplate_templates: '{{ $getTemplates() }}',
            ...
        })">
```

If doesn't work, maybe the solution is to extend from TinyEditor (AmidEsfahani\FilamentTinyEditor\TinyEditor)  and add the methods you need to implement the new template feature.

**Comment by amidesfahani** [comment]
It seems like this warning is shown by default! All templates related features have been removed in the new version.
